## importacion de screens

#:include screens/login.kv
#:include screens/mapas.kv
#:include screens/home.kv
#:include screens/reservas.kv
#:include screens/cuenta.kv
#:include screens/contacto.kv

ScreenManager:
    # es el orden en que se muestra las pantallas
    id: screen_manager


    LoginScreen:
        name: "login"
        
    # pantallas de packs
    MapasScreen:
        name: "mapas"

    # pantallas de menu
    ContactoScreen:
        name: "contacto"

    CuentaScreen:
        name: "cuenta"

    ReservasScreen:
        name: "reservas"

    HomeScreen:
        name: "home"

    



    # SettingsScreen:
    #     name: "settings"
