<ContactoView>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(30)
        spacing: dp(20)

        Label:
            text: "Contacto"
            font_size: sp(28)
            size_hint_y: None
            height: dp(50)
            halign: "left"
            valign: "middle"
            text_size: self.size
            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
            color: TEXT_PRIMARY

        Widget:
            size_hint_y: 0.2

        Button:
            text: "Instagram"
            size_hint_y: None
            height: dp(50)
            background_normal: ""
            background_color: PRIMARY
            on_press: root.open_instagram()

        Button:
            text: "Facebook"
            size_hint_y: None
            height: dp(50)
            background_normal: ""
            background_color: PRIMARY
            on_press: root.open_facebook()

        Button:
            text: "WhatsApp"
            size_hint_y: None
            height: dp(50)
            background_normal: ""
            background_color: PRIMARY
            on_press: root.open_whatsapp()

        Button:
            text: "Email"
            size_hint_y: None
            height: dp(50)
            background_normal: ""
            background_color: PRIMARY
            on_press: root.open_email()

        Widget:
