<HomeView>:
    name: 'home'

    ScrollView:
        GridLayout:
            cols: 1
            spacing: dp(10)
            size_hint_y: None
            height: self.minimum_height
            padding: dp(10), dp(20), dp(10), dp(20)

            Label:
                text: "Juega Ya!!"
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                halign: "left"
                valign: "middle"
                text_size: self.size
                color: PRIMARY_LIGHT
                font_size: sp(35)
                size_hint_y: None
                height: dp(40)
                padding: dp(0)

            Label:
                text: "Desafia a tus limites"
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                halign: "left"
                valign: "middle"
                text_size: self.size
                color: TEXT_PRIMARY
                font_size: sp(35)
                size_hint_y: None
                height: dp(40)
                padding: dp(0)

            Label:
                text: "Ofrecemos"
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                halign: "left"
                valign: "middle"
                text_size: self.size
                font_size: sp(16)
                size_hint_y: None
                height: dp(40)
                padding: dp(0)

            BoxLayout:
                size_hint_y: None
                height: dp(200)
                spacing: dp(0)
                canvas.before:
                    Color:
                        rgba: (1, 1, 0.5, 0.7)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10]
                Label:
                    text: "uniforme, armas, cascos"
                    font_size: sp(24)
                    size_hint_y: None
                    height: dp(40)
                    padding: dp(0)
                    canvas.before:
                        Color:
                            rgba: (1, 0.5, 1, 0.7)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]

            Label:
                text: "Reseñas"
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                halign: "left"
                valign: "middle"
                text_size: self.size
                font_size: sp(16)
                size_hint_y: None
                height: dp(40)
                padding: dp(0)

            BoxLayout:
                orientation: "horizontal"
                size_hint_y: None
                height: dp(200)
                spacing: dp(20)

                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    height: dp(200)
                    size_hint_x: None
                    width: dp(170)
                    canvas.before:
                        Color:
                            rgba: PRIMARY_LIGHT
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]

                    Label:
                        text: "Una de las experiencias mas increibles, indescriptibles y lo recomendo demasiado mucho"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        font_size: sp(14)
                        padding: dp(10), dp(0)
                        size_hint_y: None
                        height: dp(170)
                    Label:
                        text: "Lucas Anonimo ##"
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        halign: "center"
                        valign: "middle"
                        text_size: self.size
                        font_size: sp(18)
                        size_hint_y: None
                        height: dp(30)

                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    height: dp(200)
                    size_hint_x: None
                    width: dp(170)
                    canvas.before:
                        Color:
                            rgba: PRIMARY_LIGHT
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]

                    Label:
                        text: "Una de las experiencias mas increibles, indescriptibles y lo recomendo demasiado mucho"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        font_size: sp(14)
                        padding: dp(10), dp(0)
                        size_hint_y: None
                        height: dp(170)
                    Label:
                        text: "Lucas Anonimo ##"
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        halign: "center"
                        valign: "middle"
                        text_size: self.size
                        font_size: sp(18)
                        size_hint_y: None
                        height: dp(30)

                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    height: dp(200)
                    size_hint_x: None
                    width: dp(170)
                    canvas.before:
                        Color:
                            rgba: PRIMARY_LIGHT
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]

                    Label:
                        text: "Una de las experiencias mas increibles, indescriptibles y lo recomendo demasiado mucho"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        font_size: sp(14)
                        padding: dp(10), dp(0)
                        size_hint_y: None
                        height: dp(170)
                    Label:
                        text: "Lucas Anonimo ##"
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        halign: "center"
                        valign: "middle"
                        text_size: self.size
                        font_size: sp(18)
                        size_hint_y: None
                        height: dp(30)
