<HomeView>:
    name: 'home' #nombre clave para el  Screenmanager

    # Modos de juego
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1
        spacing: dp(0)
        padding: dp(10), dp(20), dp(10), dp(20)
        # canvas.before:
        #     Color:
        #         rgba: (0, 0, 0, 0)
        #     Rectangle:
        #         pos: self.pos
        #         size: self.size
        
        Label:
            text: "Juega Ya!!"
            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
            halign: "left" #alinear texto   
            valign: "middle" #alinear texto
            text_size: self.size #para alinear el texto
            color: (0, 1, 1, 0.5)
            font_size: sp(35) #tamano de fuente
            size_hint: 1, None #tamaño del cuadro
            height: dp(40)
            padding: dp(0)
            # canvas.before:
            #     Color: 
            #         rgba: (0, 1, 1, 0.5)
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
        Label:
            text: "Desafia a tus limites"
            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
            halign: "left" #alinear texto   
            valign: "middle" #alinear texto
            text_size: self.size #para alinear el texto
            color: (0,0,0,1)
            font_size: sp(35) #tamano de fuente
            size_hint: 1, None #tamaño del cuadro
            height: dp(40)
            padding: dp(0)
            # canvas.before:
            #     Color: 
            #         rgba: (1, 1, 1, 0.7)
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
        Label:
            text: "Ofrecemos"
            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
            halign: "left" #alinear texto   
            valign: "middle" #alinear texto
            text_size: self.size #para alinear el texto
            font_size: sp(16) #tamano de fuente
            size_hint: 1, None #tamaño del cuadro
            height: dp(40)
            padding: dp(0)
            
        BoxLayout:
            size_hint: None, None
            size: dp(400), dp(200)
            spacing: dp(0)
            canvas.before:
                Color: 
                    rgba: (1, 1, 0.5, 0.7)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [10]
            Label:
                text: "uniforme, armas, cascos"
                font_size: sp(24) #tamano de fuente
                size_hint: 1, None #tamaño del cuadro
                height: dp(40)
                padding: dp(0)
                canvas.before:
                    Color: 
                        rgba: (1, 0.5, 1, 0.7)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10]
        Label:
            text: "Reseñas"
            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
            halign: "left" #alinear texto   
            valign: "middle" #alinear texto
            text_size: self.size #para alinear el texto
            font_size: sp(16) #tamano de fuente
            size_hint: 1, None #tamaño del cuadro
            height: dp(40)
            padding: dp(0)

        # RESEÑAS DE USUARIOS
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, None
            height: dp(200)
            spacing: dp(20)
            #pos_hint: {"center_x": 0.5, "center_y": 0.5}

            # size: dp(400), dp(200)
            # canvas.before:
            #     Color: 
            #         rgba: (0, 1, 0.2, 0.7)
            #     RoundedRectangle:
            #         pos: self.pos
            #         size: self.size
            #         radius: [10]
            
            #USUAIO 1
            BoxLayout:
                orientation: "vertical"
                size_hint: None, None
                size: dp(170), dp(200)
                canvas.before:
                    Color: 
                        rgba: (0, 0.75, 0.2, 0.7)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10]
                
                Label:
                    text: "Una de las experiencias mas increibles, indescriptibles y lo recomendo demasiado mucho"
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    halign: "left" #alinear texto   
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: sp(14) #tamano de fuente
                    padding: dp(10), dp(0) 
                    # canvas.before:
                    #     Color: 
                    #         rgba: (0.8, 0.2, 0.2, 0.7)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]
                Label:
                    text: "Lucas Anonimo ##"
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    halign: "center" #alinear texto   
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: sp(18) #tamano de fuente
                    size_hint: 1, None
                    height: dp(30)
            #USUAIO 2
            BoxLayout:
                orientation: "vertical"
                size_hint: None, None
                size: dp(170), dp(200)
                canvas.before:
                    Color: 
                        rgba: (0, 0.75, 0.2, 0.7)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10]
                
                Label:
                    text: "Una de las experiencias mas increibles, indescriptibles y lo recomendo demasiado mucho"
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    halign: "left" #alinear texto   
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: sp(14) #tamano de fuente
                    padding: dp(10), dp(0) 
                    # canvas.before:
                    #     Color: 
                    #         rgba: (0.8, 0.2, 0.2, 0.7)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]
                Label:
                    text: "Lucas Anonimo ##"
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    halign: "center" #alinear texto   
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: sp(18) #tamano de fuente
                    size_hint: 1, None
                    height: dp(30)
            #USUAIO 3
            BoxLayout:
                orientation: "vertical"
                size_hint: None, None
                size: dp(170), dp(200)
                canvas.before:
                    Color: 
                        rgba: (0, 0.75, 0.2, 0.7)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10]
                
                Label:
                    text: "Una de las experiencias mas increibles, indescriptibles y lo recomendo demasiado mucho"
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    halign: "left" #alinear texto   
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: sp(14) #tamano de fuente
                    padding: dp(10), dp(0) 
                    # canvas.before:
                    #     Color: 
                    #         rgba: (0.8, 0.2, 0.2, 0.7)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]
                Label:
                    text: "Lucas Anonimo ##"
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    halign: "center" #alinear texto   
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: sp(18) #tamano de fuente
                    size_hint: 1, None
                    height: dp(30)


        BoxLayout: 
            size_hint: 1, 1
        # Navegaciones
      