<MapasView>:
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1 
        canvas.before:
            # Color:
            #     rgba: (1, 0.5, 1, 0.5)   # Fondo Azul
            # Rectangle:
            #     pos: self.pos
            #     size: self.size

           
        # Mapass
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, 1 
            spacing: dp(0)
            padding: dp(10), dp(20), dp(10), dp(10)

            # canvas.before:
            #     Color:
            #         rgba: (1, 1, 1, 0.5)   # Fondo Azul
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            
            Image:
                id: imagen_cambiable
                source: "assets/images/mapa1.png"
                allow_stretch: True
                keep_ratio: False

            
        #panel de informacion?
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(130)
            padding: dp(10), dp(0)
            canvas.before:
                Color:
                    rgba: (0.2, 0.47, 0.2, 1)

                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [15]

            BoxLayout:
                orientation: "horizontal"
                size_hint: 1, None
                height: dp(25)
                padding: dp(0)
                # canvas.before:
                #     Color:
                #         rgba: (1, 1, 1, 0.8)
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size

                Button:
                    text: "<"
                    size_hint: None, None
                    size: dp(40), dp(40)
                    on_press: imagen_cambiable.source = "assets/images/mapa2.png"
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                Label:
                    text: "Informacion Relevante"
                    size_hint: 0.2, None
                    height: dp(45)
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    font_size: dp(18)
                    halign: "center" #alinear texto
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    # canvas.before:
                    #     Color:
                    #         rgba: (0, 1, 1, 0.5)
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size 
                Button:
                    text: ">"
                    size_hint: None, None
                    size: dp(40), dp(40)
                    on_press: imagen_cambiable.source = "assets/images/mapa3.png"
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    pos_hint: {"center_x": 0.7, "center_y": 0.5}

            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(90)
                padding: dp(20), dp(0), dp(20), dp(0)
                # canvas.before:
                #     Color:
                #         rgba: (0, 1, 1, 0.5)
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size
                Label:
                    size_hint: 1, None
                    padding: dp(0)
                    height: dp(110)
                    halign: "left" #alinear texto
                    valign: "middle" #alinear texto
                    text_size: self.size #para alinear el texto
                    font_size: dp(14)
                    text: "Cantidad maxima de jugadores: 45 \nModalidades: Todos vs Todos \nCaptura la bandera \nPunto Caliente"
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    # canvas.before:
                    #     Color:
                    #         rgba: (0.5, 1, 1, 0.5)
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size
                    

