<NavBaseView>:
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1
        spacing: 0
        padding: dp(10)
        canvas.before:
            Color:
                rgba: PRIMARY_DARK
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: "horizontal"
            spacing: dp(20)
            padding: dp(10), dp(0)
            size_hint: 1, None
            height: dp(35)

            Label:
                text: "Air soft"
                font_size: sp(30)
                halign: "left"
                valign: "middle"
                text_size: self.size
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                size_hint_y: None
                height: dp(35)
                padding: dp(15)

            Label:
                text: "RMT"
                font_size: sp(18)
                size_hint: 0.2 , 0
                size_hint_y: None
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                height: dp(35)
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.1)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20]
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(70)

            FloatLayout:
                Button:
                    id: mapsBtn
                    on_press: sm.current = "mapas"
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            source: "assets/icons/mapas.png"
                            pos: self.pos
                            size: self.size

                Label:
                    text: "Mapas"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.2}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    color: (1, 1, 1, 1)
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: sm.current = "kits"
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/kits.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Kits"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.2}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

        ScreenManager:
            id: sm
            MapasView:
                name: "mapas"
            KitsView:
                name: "kits"

        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(120)
            padding: dp(20), dp(0), dp(20), dp(20)

            FloatLayout:
                orientation: "horizontal"
                size_hint: 1, None
                height: dp(80)
                padding: dp(20)
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.6)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [25]

                Button:
                    on_press: root.go_home()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 0.9)
                        Rectangle:
                            source: "assets/icons/home.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Home"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.3}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_reservas()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/reservas.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Reserves"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.3}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_contacto()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/contacto.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Contact"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.3}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_cuenta()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/profile-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Account"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.3}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_login()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.6}
                    font_size: sp(14)
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/exit.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Exit"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.3}
                    font_size: sp(14)
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)
