<ReservasView>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(10) 
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.2)
            Rectangle:
                source: "assets/images/fondo.png"
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)
            padding: dp(30), dp(30), dp(30),dp(0) 
            # canvas.before:
            #     Color:
            #         rgba: (0, 0, 1, 0.5)
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            #Conteiner de Rerservas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(200)
                padding: dp(15), dp(0) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                #Fecha y confirmacion 
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(35)
                    padding: 0 #
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Label:
                        text: "Febrero 2026 5:00 PM"
                        padding: dp(15), dp(0)
                        size_hint: 1, None
                        height: dp(35)
                        halign: "left" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        # canvas.before:
                        #     Color:
                        #         rgba: (1, 1, 1, 0.5)
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10]  
                    Label:
                        text: "120.000 $"
                        padding: dp(15), dp(0)
                        height: dp(40)
                        size_hint: 1, None
                        halign: "right" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        font_size: sp(30)
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 1                        
                    BoxLayout:
                        canvas.before:
                            Color:
                                rgba: (0, 0, 0, 0)
                            RoundedRectangle:
                                source: "assets/images/mapa1.png"
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        Image:
                            source: "assets/images/mapa1.png"
                            allow_stretch: True
                            keep_ratio: True
                            size_hint_y: None

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: 1, 1
                        
                        Label:
                            text: "Todos vs Todos como estan aqui va todo para la reserva creo yo\n 2 \n 3\n 4\n 5"
                            size_hint: 1, 1
                            padding: dp(20), dp(0)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            font_size: sp(12)
                            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                            # canvas.before:
                            #     Color:
                            #         rgba: (1, 1, 0, 0.5)
                            #     RoundedRectangle:
                            #         pos: self.pos
                            #         size: self.size
                            #         radius: [10]
                        # Label:
                        #     text: "Ubicacion"
                        #     padding: dp(20)
                        #     halign: "left" #alinear texto   
                        #     valign: "middle" #alinear texto
                        #     text_size: self.size #para alinear el texto
                        #     font_size: dp(14)
                        #     font_name: "assets/fonts/RobotoSlab-Regular.ttf"        
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(50)
                    padding: dp(15), dp(5)
                    spacing: dp(15)
                    Button:
                        text: "Cancelar"
                        background_nomal: ""
                        background_color: (0, 0, 0, 0)
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        canvas.before:
                            Color:
                                rgba: (0.5, 0, 0, 0.8)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10] 
                    Button:
                        text: "Editar"
                        background_nomal: ""
                        background_color: (0, 0, 0, 0)
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        canvas.before:
                            Color:
                                rgba: (0, 0.5, 0, 0.8)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10]

            # agregar mas reservas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(55)
                padding: dp(15), dp(0) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (0, 0.5, 0, 0.8)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                #Fecha y confirmacion 
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(55)
                    padding: 0 #
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Button:
                        text: "Crear nueva reserva +"
                        background_nomal: ""
                        background_color: (0, 0, 0, 0)
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        padding: dp(15)
                        size_hint: 1, None
                        height: dp(55)
                        halign: "center" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                   
            BoxLayout:
                size_hint: 1,1
