<LoginBase@Screen>:
    BoxLayout:
        orientation: "vertical"
        #fondo del app
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.8)   # Fondo blanco opaco
            Rectangle:
                source: "assets/images/fondo_login.png"
                pos: self.pos
                size: self.size
        #barra superior
        BoxLayout:
            orientation: "vertical"
            spacing: 0
            padding: 0

            # Caja 1
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, 1  
                spacing: 0
                padding: dp(0)
                # canvas.before:
                #     Color:
                #         rgba: (0.5, 0.5, 0.5, 0.5)  # fondo gris claro
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size

                #Login Account
                BoxLayout:
                    orientation: "vertical"
                    padding: dp(40), dp(10), dp(40), dp(0)
                    size_hint: 1, None
                    height: dp(80)
                    spacing: 0

                    Label:
                        text: "Login Account"
                        markup: True
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        halign: "left"
                        valign: "middle"
                        font_size: sp(35)
                        text_size: self.size
                        size_hint_y: None
                        height: dp(40)   # altura fija

                    Label:
                        text: "Please login with registered account"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: dp(30)   # altura fija

                #####################
                ScreenManager:
                    id: sm
                    Login:
                        name: "login"
                    NewUser:
                        name: "newuser"
                    Password:
                        name: "password"
                    
                ########################
                    
            
            # Caja 2
            BoxLayout:
                #padding: 0
                #spacing: 0
                size_hint: 1, None  
                orientation: "vertical"
                height: dp(150)
                # canvas.before:
                #     Color:
                #         rgba: (0.8, 0.5, 0.5, 1)  # fondo rojizo
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size
                # sign in
                FloatLayout:
                    padding: dp(40)
                    Button:
                        text: "Sign in"
                        pos_hint: {"center_x": 0.5, "center_y": 0.7}
                        size_hint: 0.4 , 0.2
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        height: dp(60)
                        #size_hint_y: None
                        background_normal: ""
                        background_color: (0, 0, 0, 0) #transparente
                        canvas.before:
                            Color:
                                rgba: (0.2, 0.47, 0.2, 1)
                                #rgba: (0.25, 0.65, 0.35, 1)   # color de fondo
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10] 
                        on_press: self.fill_color = (0, 1, 0, 0.5); app.root.current = "homebase"  # Llama a la función del botón
                        on_release: self.fill_color = (0, 1, 0, 0.8);  # color original al soltar el botón
 
                
                    Button:
                        text: "Created account"
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        background_normal: ""
                        size_hint: None, None
                        background_color: (0, 0, 0, 0) #transparentesize_hint: None, None
                        size: dp(120), dp(30)   
                        # canvas.before:
                        #     Color:
                        #         rgba: (0.2, 0.47, 0.2, 1)
                        #         #rgba: (0.25, 0.65, 0.35, 1)   # color de fondo
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10] 
                        on_press: self.fill_color = (0, 1, 0, 0.5); sm.current = "newuser"  # Llama a la función del botón
                        
                    Button:
                        text: "¿Recuperar contra?"
                        pos_hint: {"center_x": 0.5, "center_y": 0.3}
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        size_hint: None, None
                        background_normal: ""
                        background_color: (0, 0, 0, 0) #transparente
                        size: dp(135), dp(30)  
                        # canvas.before:
                        #     Color:
                        #         rgba: (0.2, 0.47, 0.2, 1)
                        #         #rgba: (0.25, 0.65, 0.35, 1)   # color de fondo
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10] 
                        on_press: self.fill_color = (0, 1, 0, 0.5); sm.current = "password"  # Llama a la función del botón
                        
                