<NewUser@Screen>:                    
    #####
    BoxLayout:
        orientation: "vertical"
        size_hint: 0.9, None
        padding: dp(20), dp(30)
        pos_hint: {"center_x": 0.5, "center_y": 0.4}
        height: dp(170)
        canvas.before:
            Color:
                rgba: (0.2, 0.47, 0.2, 0.8)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [15]
        
        # Email    
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(100)
            padding: [30, 0, 30, 0]
            # canvas.before:
            #     Color:
            #         rgba: (0.5, 0.5, 0.5, 0.5)  # fondo gris claro
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            Label:
                id: email
                text: "Nuevo usuario"
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                halign: "left"
                valign: "middle"
                text_size: self.size
                size_hint_y: None
                height: dp(30)   # altura más grande para que el TextInput entre bien

            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: dp(30)   # altura más grande para que el TextInput entre bien
                # canvas.before:
                #     Color:
                #         rgba: (0, 0, 0, 0.4)   
                #     RoundedRectangle:
                #         pos: self.pos
                #         size: self.size
                #         radius: [30]    
                TextInput:
                    text: "Enter your email"
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    padding: 5
                    multiline: False
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                    size_hint_y: None
                    height: dp(30)   # altura más grande para que el TextInput entre bien
                    
        #password
        BoxLayout:
            orientation: "vertical"
            padding: [30, 0, 30, 0]
            size_hint: 1, None
            height: dp(70)
            # canvas.before:
            #     Color:
            #         rgba: (0.5, 1, 0.5, 0.5)  # fondo gris claro
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            Label:
                id: password
                text: "Password"
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                halign: "left"
                valign: "middle"
                text_size: self.size
                size_hint_y: None
                height: dp(30)   # altura más grande para que el TextInput entre bien

            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: dp(30)   # altura más grande para que el TextInput entre bien
                # canvas.before:
                #     Color:
                #         rgba: (0, 0, 0, 0.2)   # color de fondo
                #     RoundedRectangle:
                #         pos: self.pos
                #         size: self.size
                #         radius: [30]    
                TextInput:
                    text: "Enter your password"
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    padding: 5
                    multiline: False
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                    size_hint_y: None
                    height: dp(30)   # altura más grande para que el TextInput entre bien
                                    

