<Cuenta@Screen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(0) 
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.4)
            Rectangle:
                source: "assets/images/fondo.png"
                pos: self.pos
                size: self.size
        
        #FONDO DE LA PAGINA
        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)
            padding: dp(10)
            # canvas.before:
            #     Color:
            #         rgba: (0, 0, 1, 0.5)
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            #Conteiner perfil
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(300)
                padding: dp(15) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 1
                    BoxLayout:
                        canvas.before:
                            Color:
                                rgba: (0, 1, 0, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        Label:
                            text: "imagen"

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: 1, 1
                        # canvas.before:
                        #     Color:
                        #         rgba: (1, 1, 0, 0.5)
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10]
                        Label:
                            padding: dp(20), dp(0)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Ronis123 \nRonny Mamani Torrez \n ronny@gmail.com\n masculino \n10684277 \n Acerca de mi: holasasa"
                            font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                            font_size: dp(14)
                            # canvas.before:
                            #     Color:
                            #         rgba: (1, 1, 0, 0.5)
                            #     RoundedRectangle:
                            #         pos: self.pos
                            #         size: self.size
                            #         radius: [10]
                        Button:
                            text: "editar"
                            size_hint: None, None
                            size: dp(100), dp(35)
                            pos_hint: {"center_x":0.5, "center_y":0.5}
                            background_normal: ""
                            background_color: (0, 0, 0, 0)
                            canvas.before:
                                Color:
                                    rgba: (0, 0.5, 0, 0.8)
                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [10]
                    

            #Conteiner de Estadisticas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(150) ##### SE MODIFICA CON LA CANTIDAD DE JUGADAS
                padding: dp(15) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (0, 0.5, 0, 0.8)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                BoxLayout:
                    size_hint: 1, None
                    height: dp(55)
                    padding: dp(0), dp(0), dp(10), dp(10) 
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Label:
                        text: "Mi historial de jugadas"
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        padding: dp(15)
                        size_hint: 1, None
                        height: dp(55)
                        font_size: sp(20)

                BoxLayout:
                    orientation: "vertical"
                    size_hint: 1, 1
                    padding: dp(0), dp(0), dp(10), dp(0) 
                    canvas.before:
                        Color:
                            rgba: (0, 0, 0, 0.5)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]
                    Label:
                        text: "Todos vs Todos: 2025: Victoria \nCaptura la bandera: 2024: Derrota"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        padding: dp(20), dp(0)
                        size_hint: 1, None 
                        height: dp(55)
                        halign: "left" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto

            BoxLayout:
                size_hint: 1,1           

            