#kivy 2.2.0

<HomeScreen>:
    # contenedor de fondo
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1
        spacing: 0
        padding: dp(10) #no hay paddin
        canvas.before:
            Color:
                #rgba: (0.18, 0.55, 0.25, 1)   # Fondo blanco opaco
                #rgba: (0.6, 0.85, 0.6, 1)
                rgba: (0.08, 0.15, 0.08, 1)

            Rectangle:
                pos: self.pos
                size: self.size

        #contenedor de del titulo y el nombre
        BoxLayout:
            orientation: "horizontal"
            spacing: dp(20)
            padding: dp(10)
            size_hint: 1, None
            height: dp(65)
            # canvas.before:
            #     Color:
            #         rgba: (1, 0, 0, 0.5)   # Fondo rojo
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            Label:
                text: "Air soft"
                font_size: sp(30) #tamano de fuente
                halign: "left" #alinear texto
                valign: "middle" #alinear texto
                text_size: self.size #para alinear el texto
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                size_hint_y: None #tamaño del cuadro
                height: dp(55)   # altura fija
                padding: dp(15)
                # canvas.before:
                #     Color: 
                #         rgba: (1, 1, 1, 0.5)
                #     RoundedRectangle:
                #         pos: self.pos
                #         size: self.size
                #         radius: [5]
            Label:
                text: "RMT"
                font_size: sp(18)
                size_hint: 0.2 , 0
                size_hint_y: None #tamaño del cuadro
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                height: dp(55)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.1)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20]
        BoxLayout:
            padding: dp(30), dp(0), dp(0), dp(0)
            size_hint: None, None
            height: dp(20)
            # canvas.before:
            #     Color: 
            #         rgba: (1, 1, 1, 0.5)
            #     RoundedRectangle:
            #         pos: self.pos
            #         size: self.size
            #         radius: [5]
            Label:
                text: "Reserva tu pack"
                size_hint: None, None
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                height: dp(30)
                # canvas.before:
                #     Color:
                #         rgba: (1, 1, 0, 0.5)   # Fondo Amarillo
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size

        #Categorias
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, None
            height: dp(65)
            spacing: dp(20)
            padding: dp(10), dp(0), dp(10), dp(10) 
            # canvas.before:
            #     Color:
            #         rgba: (1, 1, 0, 0.5)   # Fondo Amarillo
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            
            Button:
                text: "Mapas"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                font_size: sp(16) #tamano de fuente
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                size_hint: 0.3, 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(45)   # altura fija
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]
            Button:
                text: "Kits"
                font_size: sp(16)
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(45)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]
            Button:
                text: "Modos"
                font_size: sp(16)
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(45)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]
            Button:
                text: "Pública"
                font_size: sp(16)
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(45)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]
            Button:
                text: "Privada"
                font_size: sp(16)
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(45)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]
        
        # Modos de juego
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, 0.5 
            spacing: dp(20)
            padding: dp(10), dp(20), dp(10), dp(20)
            # canvas.before:
            #     Color:
            #         rgba: (0, 1, 1, 0.5)   # Fondo Azul
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            Label:
                text: "Mapa 1"
                font_size: sp(24) #tamano de fuente
                size_hint:1, 1 #tamaño del cuadro
                padding: dp(0)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.7)
                    RoundedRectangle:
                        source: "assets/images/mapa1.png"
                        pos: self.pos
                        size: self.size
                        radius: [10]
            # Label:
            #     text: "Mapa 2"
            #     font_size: sp(24) #tamano de fuente
            #     size_hint: 1, 1

            #     padding: dp(15)
            #     canvas.before:
            #         Color: 
            #             rgba: (1, 1, 1, 0.5)
            #         RoundedRectangle:
            #             pos: self.pos
            #             size: self.size
            #             radius: [5]
            # Label:
            #     text: "Mapa 3"
            #     font_size: sp(24) #tamano de fuente
            #     size_hint: 1, 0.8 
            #     padding: dp(15)
            #     canvas.before:
            #         Color: 
            #             rgba: (1, 1, 1, 0.5)
            #         RoundedRectangle:
            #             pos: self.pos
            #             size: self.size
            #             radius: [5]
        
        # Navegaciones
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(120)
            padding: dp(20), dp(0), dp(20), dp(20)
            # canvas.before:
            #     Color:
            #         rgba: (1, 0, 0, 0.5)   # Fondo Rojo
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
                    
            FloatLayout:
                orientation: "horizontal"
                size_hint: 1, None
                #pos_hint: {"center_x": 0.5, "center_y": 0.5}
                #spacing: dp(35)
                height: dp(80)
                #width: dp(300)
                padding: dp(20)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.6)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [25]
                
                Button:
                    #text: "H"
                    on_press: root.go_home()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.9)
                        Rectangle:
                            source: "assets/icons/home-green.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Home"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    color: (0.08, 0.15, 0.08, 0.8)
                    height: dp(30)
                    width: dp(30)
                    # canvas.before:
                    #     Color: 
                    #         rgba: (1, 1, 1, 0.4)
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size
                        
                Button:
                    #text: "R"
                    on_press: root.go_reservas()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/reserve-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Reserves"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "C"
                    on_press: root.go_contacto()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/contact-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Contact"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "A"
                    on_press: root.go_cuenta()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/profile-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Account"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "E"
                    on_press: root.go_login()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/exit.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Exit"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                            
