<HomeBase@Screen>:
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1
        spacing: 0
        padding: dp(10)
        canvas.before:
            Color:
                rgba: (0.08, 0.15, 0.08, 1)

            Rectangle:
                pos: self.pos
                size: self.size

        #contenedor de del titulo y el nombre
        BoxLayout:
            orientation: "horizontal"
            spacing: dp(20)
            padding: dp(10), dp(0)
            size_hint: 1, None
            height: dp(35)
            
            Label:
                text: "Air soft"
                font_size: sp(30) #tamano de fuente
                halign: "left" #alinear texto
                valign: "middle" #alinear texto
                text_size: self.size #para alinear el texto
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                size_hint_y: None #tamaño del cuadro
                height: dp(35)   # altura fija
                padding: dp(15)
                
            Label:
                text: "RMT"
                font_size: sp(18)
                size_hint: 0.2 , 0
                size_hint_y: None #tamaño del cuadro
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                height: dp(35)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.1)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20]


        ## categorias
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(70)

            FloatLayout:
                Button:
                    id: btn_mapas
                    #text: "Mapas"
                    on_press: sm.current = "mapas"; root.cambiar_color_nav(btn_mapas, lb_mapas)
                    on_release: root.reset_color_nave(btn_kits, lb_kits); root.reset_color_nave(btn_modos, lb_modos); root.reset_color_nave(btn_publica, lb_publica); root.reset_color_nave(btn_privada, lb_privada)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            source: "assets/icons/mapas.png"
                            pos: self.pos
                            size: self.size
                    
                Label:
                    id: lb_mapas
                    text: "Mapas"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    color: (1, 1, 1, 1)
                    height: dp(30)
                    width: dp(30)
                        
                Button:
                    id: btn_kits
                    #text: "kits"
                    on_press: sm.current = "kits"; root.cambiar_color_nav(btn_kits, lb_kits)
                    on_release: root.reset_color_nave(btn_mapas, lb_mapas); root.reset_color_nave(btn_modos, lb_modos); root.reset_color_nave(btn_publica, lb_publica); root.reset_color_nave(btn_privada, lb_privada)

                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/kits.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_kits
                    text: "Kits"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "Modos"
                    id: btn_modos
                    on_press: sm.current = "modos"; root.cambiar_color_nav(btn_modos, lb_modos)
                    on_release: root.reset_color_nave(btn_mapas, lb_mapas); root.reset_color_nave(btn_kits, lb_kits); root.reset_color_nave(btn_publica, lb_publica); root.reset_color_nave(btn_privada, lb_privada)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/modos.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_modos
                    text: "Modos"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

                Button:
                    id: btn_publica
                    #text: "publica"
                    on_press: sm.current = "publica"; root.cambiar_color_nav(btn_publica, lb_publica)
                    on_release: root.reset_color_nave(btn_mapas, lb_mapas); root.reset_color_nave(btn_kits, lb_kits); root.reset_color_nave(btn_modos, lb_modos); root.reset_color_nave(btn_privada, lb_privada)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/publica.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_publica
                    text: "publica"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

                Button:
                    id: btn_privada
                    #text: "privada"
                    on_press: sm.current = "privada"; root.cambiar_color_nav(btn_privada, lb_privada) ###########
                    on_release: root.reset_color_nave(btn_mapas, lb_mapas); root.reset_color_nave(btn_kits, lb_kits); root.reset_color_nave(btn_modos, lb_modos); root.reset_color_nave(btn_publica, lb_publica)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/privada.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_privada
                    text: "privada"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)
        #
        ###################
        ScreenManager: 
            id: sm
            Mapas: 
                name: "mapas"
            Kits:
                name: "kits"
            Modos:
                name: "modos"
            Publica:
                name: "publica"
            Privada:
                name: "privada"
            Reservas:
                name: "reservas"
            Contacto:
                name: "contacto"
            Cuenta:
                name: "cuenta"
            Home: 
                name: "home"
            
        ###############

        # Navegaciones
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(120)
            padding: dp(20), dp(0), dp(20), dp(20)
                    
            FloatLayout:
                orientation: "horizontal"
                size_hint: 1, None
                height: dp(80)
                padding: dp(20)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.6)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [25]
                        
                Button:
                    id: btn_reservas
                    on_press: sm.current = "reservas"; root.cambiar_color_nav(btn_reservas, lb_reservas)
                    on_release: root.reset_color_nave(btn_home, lb_home); root.reset_color_nave(btn_contacto, lb_contacto); root.reset_color_nave(btn_cuenta, lb_cuenta); root.reset_color_nave(btn_login, lb_login)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/reserve-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_reservas
                    text: "Reserves"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                
                Button:
                    id: btn_contacto
                    on_press: sm.current = "contacto"; root.cambiar_color_nav(btn_contacto, lb_contacto)
                    on_release: root.reset_color_nave(btn_home, lb_home); root.reset_color_nave(btn_reservas, lb_reservas); root.reset_color_nave(btn_cuenta, lb_cuenta); root.reset_color_nave(btn_login, lb_login)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/contact-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_contacto
                    text: "Contact"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    id: btn_home
                    on_press: sm.current = "home"; root.cambiar_color_nav(btn_home, lb_home)
                    on_release: root.reset_color_nave(btn_reservas, lb_reservas); root.reset_color_nave(btn_contacto, lb_contacto); root.reset_color_nave(btn_cuenta, lb_cuenta); root.reset_color_nave(btn_login, lb_login)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.9)
                        Rectangle:
                            source: "assets/icons/home-green.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_home
                    text: "Home"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (0.08, 0.15, 0.08, 1)
                    height: dp(30)
                    width: dp(30)


                Button:
                    id: btn_cuenta
                    on_press: sm.current = "cuenta"; root.cambiar_color_nav(btn_cuenta, lb_cuenta)
                    on_release: root.reset_color_nave(btn_home, lb_home); root.reset_color_nave(btn_reservas, lb_reservas); root.reset_color_nave(btn_contacto, lb_contacto); root.reset_color_nave(btn_login, lb_login)
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/profile-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_cuenta
                    text: "Account"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    id: btn_login
                    on_press: app.root.current = "loginbase"; root.cambiar_color_nav(btn_login, lb_login)
                    on_release: root.reset_color_nave(btn_home, lb_home); root.reset_color_nave(btn_reservas, lb_reservas); root.reset_color_nave(btn_contacto, lb_contacto); root.reset_color_nave(btn_cuenta, lb_cuenta)  
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/exit.png"
                            pos: self.pos
                            size: self.size
                Label:
                    id: lb_login
                    text: "Exit"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                            
