#kivy 2.2.0

<HomeScreen>:
    # contenedor de fondo
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1
        spacing: 0
        padding: dp(10) #no hay paddin
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.5)   # Fondo blanco opaco
            Rectangle:
                pos: self.pos
                size: self.size

        #contenedor de del titulo y el nombre
        BoxLayout:
            orientation: "horizontal"
            spacing: dp(20)
            padding: dp(10)
            size_hint: 1, None
            height: dp(100)
            canvas.before:
                Color:
                    rgba: (1, 0, 0, 0.5)   # Fondo rojo
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Air soft"
                font_size: sp(18) #tamano de fuente
                halign: "left" #alinear texto
                valign: "middle" #alinear texto
                text_size: self.size #para alinear el texto
                size_hint_y: None #tamaño del cuadro
                height: dp(55)   # altura fija
                padding: dp(15)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "Ronny"
                font_size: sp(18)
                size_hint: 0.2 , 0
                size_hint_y: None #tamaño del cuadro
                height: dp(55)
                canvas.before:
                    Color: 
                        rgba: (1, 0, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
        
        #Categorias
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, None
            spacing: dp(20)
            padding: dp(10) 
            canvas.before:
                Color:
                    rgba: (1, 1, 0, 0.5)   # Fondo Amarillo
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "mapas"
                font_size: sp(16) #tamano de fuente
                size_hint: 0.3, 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(55)   # altura fija
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "kits"
                font_size: sp(16)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(55)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "kits"
                font_size: sp(16)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(55)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "kits"
                font_size: sp(16)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(55)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "kits"
                font_size: sp(16)
                size_hint: 0.3 , 0.3
                size_hint_y: None #tamaño del cuadro
                height: dp(55)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
        
        # Modos de juego
        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, 0.5 
            spacing: dp(20)
            padding: dp(30)
            canvas.before:
                Color:
                    rgba: (0, 1, 1, 0.5)   # Fondo Azul
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Mapa 1"
                font_size: sp(24) #tamano de fuente
                size_hint:1, 0.8 #tamaño del cuadro
                padding: dp(15)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "Mapa 2"
                font_size: sp(24) #tamano de fuente
                size_hint: 1, 1
                padding: dp(15)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
            Label:
                text: "Mapa 3"
                font_size: sp(24) #tamano de fuente
                size_hint: 1, 0.8 
                padding: dp(15)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [5]
        
        # Navegaciones
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(100)
            padding: dp(50), dp(0), dp(50), dp(20)
            # canvas.before:
            #     Color:
            #         rgba: (1, 0, 0, 0.5)   # Fondo Rojo
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
                    
            BoxLayout:
                orientation: "horizontal"
                size_hint: 1, None
                spacing: dp(25)
                height: dp(50)
                # canvas.before:
                #     Color: 
                #         rgba: (1, 0, 1, 0.5)
                #     RoundedRectangle:
                #         pos: self.pos
                #         size: self.size
                
                Button:
                    text: "Home"
                    on_press: root.go_home()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    font_size: sp(14) 
                    size_hint: 1, None
                    height: dp(50)
                    padding: dp(15)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [5]                    
                Button:
                    text: "Reservas"
                    on_press: root.go_reservas()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    font_size: sp(14) 
                    size_hint: 1, None
                    height: dp(50)   
                    padding: dp(15)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [5]
                Button:
                    on_press: root.go_contacto()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    text: "Contactos"
                    font_size: sp(14) 
                    size_hint: 1, None
                    height: dp(50)
                    padding: dp(15)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [5]
                Button:
                    text: "Cuenta"
                    on_press: root.go_cuenta()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    font_size: sp(14) 
                    size_hint: 1, None
                    height: dp(50)
                    padding: dp(15)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [5]
                            
