<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        #fondo del app
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.8)   # Fondo blanco opaco
            Rectangle:
                source: "assets/images/fondo_login.png"
                pos: self.pos
                size: self.size
        #barra superior
        BoxLayout:
            orientation: "vertical"
            spacing: 0
            padding: 0

            # Caja 1
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, 1  
                spacing: 0
                padding: dp(0)
                # canvas.before:
                #     Color:
                #         rgba: (0.5, 0.5, 0.5, 0.5)  # fondo gris claro
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size

                #Login Account
                BoxLayout:
                    orientation: "vertical"
                    padding: dp(40), dp(10), dp(40), dp(0)
                    size_hint: 1, None
                    height: dp(80)
                    spacing: 0

                    Label:
                        text: "Login Account"
                        markup: True
                        font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                        halign: "left"
                        valign: "middle"
                        font_size: sp(35)
                        text_size: self.size
                        size_hint_y: None
                        height: dp(40)   # altura fija

                    Label:
                        text: "Please login with registered account"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: dp(30)   # altura fija

                # Email    
                BoxLayout:
                    orientation: "vertical"
                    size_hint: 1, 1
                    #height: dp(200)
                    padding: [30, 0, 30, 0]
                    # canvas.before:
                    #     Color:
                    #         rgba: (0.5, 0.5, 0.5, 0.5)  # fondo gris claro
                    #     Rectangle:
                    #         pos: self.pos
                    #         size: self.size

                    Label:
                        id: email
                        text: "Email"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: dp(30)   # altura más grande para que el TextInput entre bien

                    BoxLayout:
                        orientation: "vertical"
                        size_hint_y: None
                        height: dp(30)   # altura más grande para que el TextInput entre bien
                        canvas.before:
                            Color:
                                rgba: (0, 0, 0, 0.4)   
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [30]    
                        TextInput:
                            text: "Enter your email"
                            font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                            padding: 5
                            multiline: False
                            halign: "left"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(30)   # altura más grande para que el TextInput entre bien
                            
                #password
                BoxLayout:
                    orientation: "vertical"
                    padding: [30, 0, 30, 0]
                    size_hint: 1, None
                    height: dp(70)

                    Label:
                        id: password
                        text: "Password"
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: dp(30)   # altura más grande para que el TextInput entre bien

                    BoxLayout:
                        orientation: "vertical"
                        size_hint_y: None
                        height: dp(30)   # altura más grande para que el TextInput entre bien
                        # canvas.before:
                        #     Color:
                        #         rgba: (0, 0, 0, 0.2)   # color de fondo
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [30]    
                        TextInput:
                            text: "Enter your password"
                            font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                            padding: 5
                            multiline: False
                            halign: "left"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: dp(30)   # altura más grande para que el TextInput entre bien
                                           
            
            # Caja 2
            BoxLayout:
                #padding: 0
                #spacing: 0
                size_hint: 1, 0.6  
                orientation: "vertical"
                size_hint: 1, None
                height: dp(200)
                # canvas.before:
                #     Color:
                #         rgba: (0.8, 0.5, 0.5, 1)  # fondo rojizo
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size
                # sign in
                FloatLayout:
                    padding: dp(40)
                    Button:
                        text: "Sign in"
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        size_hint: 0.4 , 0.2
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        height: dp(50)
                        #size_hint_y: None
                        background_normal: ""
                        background_color: (0, 0, 0, 0) #transparente
                        canvas.before:
                            Color:
                                rgba: (0.2, 0.47, 0.2, 1)
                                #rgba: (0.25, 0.65, 0.35, 1)   # color de fondo
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10] 
                        on_press: self.fill_color = (0, 1, 0, 0.5); root.login_app(email.text, password.text)  # Llama a la función del botón
                        on_release: self.fill_color = (0, 1, 0, 0.8);  # color original al soltar el botón
 
                
                    Label:
                        text: "Created account"
                        pos_hint: {"center_x": 0.5, "center_y": 0.3}
                        font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                        size_hint_y: None
                        height: dp(30)  
                