<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        #fondo del app
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.5)   # Fondo blanco opaco
            Rectangle:
                pos: self.pos
                size: self.size
        #barra superior
        BoxLayout:
            orientation: "vertical"
            spacing: 0
            padding: 0

            # Caja 1
            BoxLayout:
                orientation: "vertical"
                spacing: 0
                padding: 0
                canvas.before:
                    Color:
                        rgba: (0.5, 0.5, 0.5, 1)  # fondo gris claro
                    Rectangle:
                        pos: self.pos
                        size: self.size
                BoxLayout:
                    orientation: "vertical"
                    padding: [30, 0, 0, 0]
                    spacing: 0

                    Label:
                        text: "Login Account"
                        font_name: "assets/fonts/RobotoSlab.ttf"
                        halign: "left"
                        valign: "middle"
                        font_size: "24sp"
                        text_size: self.size
                        size_hint_y: None
                        height: 40   # altura fija

                    Label:
                        text: "Please login with registered account"
                        font_name: "assets/fonts/RobotoSlab.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: 30   # altura fija

                        
                BoxLayout:
                    orientation: "vertical"
                    padding: [30, 0, 30, 0]

                    Label:
                        text: "Email"
                        font_name: "assets/fonts/RobotoSlab.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: 30   # altura más grande para que el TextInput entre bien

                    BoxLayout:
                        orientation: "vertical"
                        size_hint_y: None
                        height: 30   # altura más grande para que el TextInput entre bien
                        canvas.before:
                            Color:
                                rgba: (0, 0, 0, 0.2)   # color de fondo
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [30]    
                        TextInput:
                            text: "Enter your email"
                            font_name: "assets/fonts/RobotoSlab.ttf"
                            padding: 5
                            multiline: False
                            halign: "left"
                            valign: "middle"
                            text_size: self.size
                            size_hint_y: None
                            height: 30   # altura más grande para que el TextInput entre bien
                            

                BoxLayout:
                    padding: [30, 0, 0, 0]
                    orientation: "vertical"
                    Label:
                        text: "Password"
                        font_name: "assets/fonts/RobotoSlab.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: 30   # altura fija
                    Label:
                        text: "Creacte yout password"
                        font_name: "assets/fonts/RobotoSlab.ttf"
                        halign: "left"
                        valign: "middle"
                        text_size: self.size
                        size_hint_y: None
                        height: 30   # altura fija                  
                

            # Caja 2
            FloatLayout:
                canvas.before:
                    Color:
                        rgba: (0.8, 0.5, 0.5, 1)  # fondo rojizo
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    text: "Caja 2"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
