<MapasScreen>:
    BoxLayout:
        orientation: "vertical"
        size_hint: 1, 1
        spacing: 0
        padding: dp(10)
        canvas.before:
            Color:
                rgba: (0.08, 0.15, 0.08, 1)

            Rectangle:
                pos: self.pos
                size: self.size

        #contenedor de del titulo y el nombre
        BoxLayout:
            orientation: "horizontal"
            spacing: dp(20)
            padding: dp(10), dp(0)
            size_hint: 1, None
            height: dp(35)
            
            Label:
                text: "Air soft"
                font_size: sp(30) #tamano de fuente
                halign: "left" #alinear texto
                valign: "middle" #alinear texto
                text_size: self.size #para alinear el texto
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                size_hint_y: None #tamaño del cuadro
                height: dp(35)   # altura fija
                padding: dp(15)
                
            Label:
                text: "RMT"
                font_size: sp(18)
                size_hint: 0.2 , 0
                size_hint_y: None #tamaño del cuadro
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                height: dp(35)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.1)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20]


        ############333
        ## categorias
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(70)

            FloatLayout:
                Button:
                    #text: "Mapas"
                    on_press: root.go_mapas()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            source: "assets/icons/mapas.png"
                            pos: self.pos
                            size: self.size
                    
                Label:
                    text: "Mapas"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                    color: (1, 1, 1, 1)
                    height: dp(30)
                    width: dp(30)
                        
                Button:
                    #text: "kits"
                    on_press: root.go_reservas()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/kits.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Kits"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "Modos"
                    on_press: root.go_contacto()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/modos.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Modos"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "publica"
                    on_press: root.go_cuenta()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/publica.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "publica"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

                Button:
                    #text: "privada"
                    on_press: root.go_login()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/privada.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "privada"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.2}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    color: (1, 1, 1, 0.5)
                    height: dp(30)
                    width: dp(30)

        
        # Mapass
        

        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, 0.5 
            spacing: dp(20)
            padding: dp(10), dp(20), dp(10), dp(20)

            # canvas.before:
            #     Color:
            #         rgba: (1, 1, 1, 0.5)   # Fondo Azul
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            
            Image:
                id: imagen_cambiable
                source: "assets/images/mapa1.png"
                allow_stretch: True
                keep_ratio: False

            

                    

        BoxLayout:
            orientation: "horizontal"
            size_hint: 1, None
            height: dp(40)
            padding: dp(10), dp(0)
            canvas.before:
                Color:
                    rgba: (1, 1, 1, 0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
    
            Button:
                text: "<"
                size_hint: None, None
                size: dp(40), dp(40)
                on_press: imagen_cambiable.source = "assets/images/mapa2.png"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
            Label:
                text: "Informacion Relevante"
                size_hint: 0.2, None
                height: dp(45)
                font_name: "assets/fonts/RobotoSlab-Bold.ttf"
                font_size: dp(18)
                halign: "center" #alinear texto
                valign: "middle" #alinear texto
                text_size: self.size #para alinear el texto
                pos_hint: {"center_x": 0.5, "center_y": 0.5}

                # canvas.before:
                #     Color:
                #         rgba: (0, 1, 1, 0.5)
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size 
            Button:
                text: ">"
                size_hint: None, None
                size: dp(40), dp(40)
                on_press: imagen_cambiable.source = "assets/images/mapa3.png"
                background_normal: ""
                background_color: (0, 0, 0, 0)
                pos_hint: {"center_x": 0.7, "center_y": 0.5}

        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(90)
            padding: dp(20), dp(0), dp(20), dp(0)
            canvas.before:
                Color:
                    rgba: (1, 1, 1, 0.5)
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                size_hint: 1, None
                padding: dp(0)
                height: dp(110)
                halign: "left" #alinear texto
                valign: "middle" #alinear texto
                text_size: self.size #para alinear el texto
                font_size: dp(14)
                text: "Cantidad maxima de jugadores: 45 \nModalidades: Todos vs Todos \nCaptura la bandera \nPunto Caliente"
                font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                # canvas.before:
                #     Color:
                #         rgba: (0.5, 1, 1, 0.5)
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size
                

        # Navegaciones
        BoxLayout:
            orientation: "vertical"
            size_hint: 1, None
            height: dp(120)
            padding: dp(20), dp(0), dp(20), dp(20)
                    
            FloatLayout:
                orientation: "horizontal"
                size_hint: 1, None
                height: dp(80)
                padding: dp(20)
                canvas.before:
                    Color: 
                        rgba: (1, 1, 1, 0.6)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [25]
                
                Button:
                    on_press: root.go_home()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.9)
                        Rectangle:
                            source: "assets/icons/home-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Home"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.1, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)
                        
                Button:
                    on_press: root.go_reservas()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.30, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30) 
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/reserve-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Reserves"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.3, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_contacto()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/contact-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Contact"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_cuenta()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/profile-white.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Account"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.7, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                Button:
                    on_press: root.go_login()
                    background_normal: ""
                    background_color: (0, 0, 0, 0)
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.6}
                    font_size: sp(14) 
                    height: dp(30)
                    width: dp(30)  
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        Rectangle:
                            source: "assets/icons/exit.png"
                            pos: self.pos
                            size: self.size
                Label:
                    text: "Exit"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.9, "center_y": 0.3}
                    font_size: sp(14) 
                    font_name: "assets/fonts/RobotoSlab-Regular.ttf"
                    height: dp(30)
                    width: dp(30)

                            
