<Reservas@Screen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(10) 
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.2)
            Rectangle:
                source: "assets/images/fondo.png"
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)
            padding: dp(30), dp(30), dp(30),dp(0) 
            # canvas.before:
            #     Color:
            #         rgba: (0, 0, 1, 0.5)
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            #Conteiner de Rerservas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(200)
                padding: dp(15), dp(0) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                #Fecha y confirmacion 
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(55)
                    padding: 0 #
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Label:
                        padding: dp(15)
                        size_hint: 1, None
                        height: dp(55)
                        halign: "left" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                        text: "Febrero 2026 5:00 PM"
                    Label:
                        padding: dp(15)
                        height: dp(55)
                        size_hint: 1, None
                        text: "confirmado XXX"
                        halign: "right" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 1
                    BoxLayout:

                        canvas.before:
                            Color:
                                rgba: (0, 1, 0, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        Label:
                            text: "imagen"
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: 1, 1
                        # canvas.before:
                        #     Color:
                        #         rgba: (1, 1, 0, 0.5)
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10]
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Todos vs Todos"
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Ubicacion"        
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(50)
                    Label:
                        text: "Cancelar"
                    Label:
                        text: "Confirmar"

            #Conteiner de Rerservas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(200)
                padding: dp(15), dp(0) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                #Fecha y confirmacion 
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(55)
                    padding: 0 #
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Label:
                        padding: dp(15)
                        size_hint: 1, None
                        height: dp(55)
                        halign: "left" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                        text: "Febrero 2026 5:00 PM"
                    Label:
                        padding: dp(15)
                        height: dp(55)
                        size_hint: 1, None
                        text: "confirmado XXX"
                        halign: "right" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 1
                    BoxLayout:

                        canvas.before:
                            Color:
                                rgba: (0, 1, 0, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        Label:
                            text: "imagen"
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: 1, 1
                        # canvas.before:
                        #     Color:
                        #         rgba: (1, 1, 0, 0.5)
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10]
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Todos vs Todos"
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Ubicacion"        
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(50)
                    Label:
                        text: "Cancelar"
                    Label:
                        text: "Confirmar"
            

            BoxLayout:
                size_hint: 1,1
