<ReservasScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(10) 
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.4)
            Rectangle:
                source: "assets/images/fondo.png"
                pos: self.pos
                size: self.size
        BoxLayout:
            size_hint: 1, None
            height: dp(55)
            # canvas.before:
            #     Color: 
            #         rgba: (1, 0, 0, 0.5)
            #     RoundedRectangle:
            #         pos: self.pos
            #         size: self.size
            #         radius: [5]
            Label:
                text: "RESERVAS"


        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)
            padding: dp(30), dp(30), dp(30),dp(0) 
            # canvas.before:
            #     Color:
            #         rgba: (0, 0, 1, 0.5)
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            #Conteiner de Rerservas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(200)
                padding: dp(15), dp(0) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                #Fecha y confirmacion 
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(55)
                    padding: 0 #
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Label:
                        padding: dp(15)
                        size_hint: 1, None
                        height: dp(55)
                        halign: "left" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                        text: "Febrero 2026 5:00 PM"
                    Label:
                        padding: dp(15)
                        height: dp(55)
                        size_hint: 1, None
                        text: "confirmado XXX"
                        halign: "right" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 1
                    BoxLayout:

                        canvas.before:
                            Color:
                                rgba: (0, 1, 0, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        Label:
                            text: "imagen"
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: 1, 1
                        # canvas.before:
                        #     Color:
                        #         rgba: (1, 1, 0, 0.5)
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10]
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Todos vs Todos"
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Ubicacion"        
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(50)
                    Label:
                        text: "Cancelar"
                    Label:
                        text: "Confirmar"

            #Conteiner de Rerservas
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(200)
                padding: dp(15), dp(0) #
                spacing: 0 #
                canvas.before:
                    Color:
                        rgba: (1, 1, 1, 0.5)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10] 

                #Fecha y confirmacion 
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(55)
                    padding: 0 #
                    spacing: 0 #
                    # canvas.before:
                    #     Color:
                    #         rgba: (1, 0, 0, 0.5)
                    #     RoundedRectangle:
                    #         pos: self.pos
                    #         size: self.size
                    #         radius: [10]  
                    Label:
                        padding: dp(15)
                        size_hint: 1, None
                        height: dp(55)
                        halign: "left" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto
                        text: "Febrero 2026 5:00 PM"
                    Label:
                        padding: dp(15)
                        height: dp(55)
                        size_hint: 1, None
                        text: "confirmado XXX"
                        halign: "right" #alinear texto   
                        valign: "middle" #alinear texto
                        text_size: self.size #para alinear el texto

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 1
                    BoxLayout:

                        canvas.before:
                            Color:
                                rgba: (0, 1, 0, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [10]
                        Label:
                            text: "imagen"
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: 1, 1
                        # canvas.before:
                        #     Color:
                        #         rgba: (1, 1, 0, 0.5)
                        #     RoundedRectangle:
                        #         pos: self.pos
                        #         size: self.size
                        #         radius: [10]
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Todos vs Todos"
                        Label:
                            padding: dp(20)
                            halign: "left" #alinear texto   
                            valign: "middle" #alinear texto
                            text_size: self.size #para alinear el texto
                            text: "Ubicacion"        
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: dp(50)
                    Label:
                        text: "Cancelar"
                    Label:
                        text: "Confirmar"
            

            BoxLayout:
                size_hint: 1,1

            #Navegaciones
            BoxLayout:
                orientation: "vertical"
                size_hint: 1, None
                height: dp(120)
                padding: dp(40), dp(0), dp(40), dp(20)
                # canvas.before:
                #     Color:
                #         rgba: (1, 0, 0, 0.5)   # Fondo Rojo
                #     Rectangle:
                #         pos: self.pos
                #         size: self.size
            
                BoxLayout:
                    orientation: "horizontal"
                    size_hint: None, None
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    spacing: dp(30)
                    height: dp(80)
                    width: dp(300)
                    padding: dp(20)
                    canvas.before:
                        Color: 
                            rgba: (1, 1, 1, 0.5)
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                    
                    Button:
                        text: "H"
                        on_press: root.go_home()
                        background_normal: ""
                        background_color: (0, 0, 0, 0)
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        font_size: sp(14) 
                        size_hint: None, None
                        height: dp(40)
                        width: dp(40)
                        padding: dp(15)
                        canvas.before:
                            Color: 
                                rgba: (1, 1, 1, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [5]                    
                    Button:
                        text: "R"
                        on_press: root.go_reservas()
                        background_normal: ""
                        background_color: (0, 0, 0, 0)
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        font_size: sp(14) 
                        size_hint: None, None
                        height: dp(40) 
                        width: dp(40)  
                        padding: dp(15)
                        canvas.before:
                            Color: 
                                rgba: (1, 1, 1, 0.8)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [5]
                    Button:
                        text: "C"
                        on_press: root.go_contacto()
                        background_normal: ""
                        background_color: (0, 0, 0, 0)
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        font_size: sp(14) 
                        size_hint: None, None
                        height: dp(40)
                        width: dp(40)  
                        padding: dp(15)
                        canvas.before:
                            Color: 
                                rgba: (1, 1, 1, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [5]
                    Button:
                        text: "A"
                        on_press: root.go_cuenta()
                        background_normal: ""
                        background_color: (0, 0, 0, 0)
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        font_size: sp(14) 
                        size_hint: None, None
                        height: dp(40)
                        width: dp(40)  
                        padding: dp(15)
                        canvas.before:
                            Color: 
                                rgba: (1, 1, 1, 0.5)
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [5]
                                
